Vagrant.configure("2") do |config|
  config.vm.define "cbeauraiS" do |cbeauraiS|
    cbeauraiS.vm.box = "generic/alpine319"
    cbeauraiS.vm.hostname = "cbeauraiS"
    cbeauraiS.vm.synced_folder "./scripts", "/scripts"
    cbeauraiS.vm.synced_folder "./confs", "/confs"
    cbeauraiS.vm.provider "virtualbox" do |v|
      v.name = "cbeauraiS"
      v.memory = 1024
      v.cpus = 1
      cbeauraiS.vm.network "private_network", ip: "192.168.56.110"
    end
    cbeauraiS.vm.provision "shell", path: "scripts/install_k3s_master.sh"
  end
end