Vagrant.configure("2") do |config|
  config.vm.define "cbeauraiS" do |cbeauraiS|
    cbeauraiS.vm.box = "generic/alpine319"
    cbeauraiS.vm.hostname = "cbeauraiS"
    cbeauraiS.vm.synced_folder "./config", "/config"
    cbeauraiS.vm.provider "virtualbox" do |v|
      v.name = "cbeaurai"
      v.memory = 1024
      v.cpus = 1
      cbeauraiS.vm.network "private_network", ip: "192.168.56.110"
    end
    cbeauraiS.vm.provision "shell", path: "config/install_k3s_master.sh"
  end
  config.vm.define "rkhelifSW" do |rkhelifSW|
    rkhelifSW.vm.box = "generic/alpine319"
    rkhelifSW.vm.hostname = "rkhelifSW"
    rkhelifSW.vm.synced_folder "./config", "/config"
    rkhelifSW.vm.provider "virtualbox" do |v|
      v.name = "rkhelif"
      v.memory = 1024
      v.cpus = 1
      rkhelifSW.vm.network "private_network", ip: "192.168.56.111"
    end
    rkhelifSW.vm.provision "shell", path: "config/install_k3s_agent.sh"
  end
end